<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>class_contain_text_following_sibling</name>
   <tag></tag>
   <elementGuidId>1e533557-3618-41c6-a5fb-795fcf3d7e91</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a12d8f31-3b09-43d1-978b-3a7c82373103</webElementGuid>
   </webElementProperties>
   <locator>//${class}[contains(@text,'${text}')]/following-sibling::*[1]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
